# Generated by Django 3.0.3 on 2020-03-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
